// Import version from the generated version.json file
// This file is generated by the generate-icons script which reads the actual installed version
import versionData from '@/data/version.json';

/**
 * Gets the installed version of stera-icons
 * This reads from the version.json file generated by the generate-icons script
 */
export const STERA_ICONS_VERSION = versionData.version;

